
deps:
  input_vcf: test/data/test.hg19.vcf
  input_psam: test/data/test.psam
  id_map: test/data/id_map.tsv

outs:
  post_qc_plink: test/results/qc/update_sex_ancestry
  
refs:
  container: resources/imputation/SNP_imputation_1000g_hg38.sif
  1000g:
    pgen: "resources/1000G/all_phase3_filtered.pgen"
    pvar: "resources/1000G/all_phase3_filtered.pvar"
    psam: "resources/1000G/all_phase3_filtered.psam"

params:
  indiv_missingness_mind: 0.05

out_dir: test/results/

log_dir: logs/imputation